name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
- authors:
defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: page
